[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "glassbox"
version = "0.1.0"
description = "White-box AutoML library"
requires-python = ">=3.9"

# Runtime dependencies
# Install with `pip install .`
dependencies = [
    "numpy",
]

# Dev dependencies
# Install with `pip install .[dev]`
[project.optional-dependencies]
dev = [
    "black",
    "ruff",
    "mkdocs<2",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
    "mkdocs-kroki-plugin",
]

[tool.setuptools.packages.find]
include = [
    "glassbox",
    "glassbox.*",
]

[tool.black]
line-length = 90
target-version = ["py311"]

[tool.ruff]
ignore = ["E501"]
select = ["E", "F", "W", "I"]
fix = true
